language: ruby

services:
  - mysql

before_install:
  - gem update --system --no-document

script:
  - cp config/.travis.database.yml config/database.yml
  - bin/rails db:setup RAILS_ENV=test
  - bundle exec rspec
