# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16b9640ac78e2175ffee8fb018c57d003b25d7a7e34e128da49942a693a5bf213544d259d6efa6e0845672a3ee51e5356a6e5419bd38c6f786e55c727e0e83fa

test:
  secret_key_base: 5ad2be55ec42d277cf249b796f8c28a53d3e7c6966dbccba54d571020026b6a38e9363b0f7d9ce71a24cd5043778d81fdf3cc6e4d40b4b276b345351f34dee65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
